### ISSUE TITLE
Changing context prop breaks cursor

### ISSUE THREAD

**Issue by michaelKurowski** [tzfun/vue-web-terminal#26] opened 2023-01-06 17:29 UTC
**Bug description**
Once the `context` prop changes on the terminal vue component, the feature of moving the cursor with arrow keys starts to malfunction. The result is that once that happens, the user is unable to reliably edit his currently typed command.

**Steps to reproduce**
1. Initialize Vue Terminal with some base props
2. Modify the  `context` prop so that it has different length than before
3. Start writing some command in the terminal, do not send it. 
4. Press left arrow, so that the cursor moves left
5. Instead of moving one char to the left, the cursor moves to a seemingly random position

**Reproduce environment:**
 - OS: Manjaro Linux
 - Browser 102.0.5005.115 (Official Build) (64-bit)
 - Version 3.1.3

**Comment by tzfun** [comment] 2023-01-18 03:29
I can't reproduce your problem, and I created a codesandbox, you try it in your environment to see if it appears, if it can show that this is a specific device bug, I can't appear in the Mac environment, if it does not appear, you should consider whether there is a cache when using your environment?

codesandbox：[https://codesandbox.io/s/rough-thunder-hh3yuj](https://codesandbox.io/s/rough-thunder-hh3yuj)

**Comment by michaelKurowski** [comment] 2023-01-22 13:15
I also don't encounter this issue anymore. I don't think it was a cache as 3 other ppl encountered it, one of them tried the app for the first time. :thinking: 
Other variables that might have contributed were:
- I've had more than one terminal window open
- I've been using dragging config on both of them

**Comment by tzfun** [comment] 2023-01-30 08:11
I tested two instances according to the operation steps you provided, and I still didn’t find the problem of cursor misalignment, but I found another dragging bug: multi-instance dragging will only take effect for one instance😅

In the next version I will fix this dragging bug and I will also try to review the logic code of the cursor position calculation, if it exists and fix it, I will propose it in the version update log.

**Comment by michaelKurowski** [comment] 2023-02-05 19:58
We catched the error again and the windows are no longer draggable, I'll let you know once we have a solid way to reproduce it.

**Comment by tzfun** [comment] 2023-02-06 02:20
OK, thanks. The update of Vue3 will be delayed for a while, because we are currently rewriting a version of Vue3 with TS.

**Comment by tzfun** [comment] 2023-03-02 06:07
#39

**Comment by tzfun** [comment] 2023-03-07 08:56
@michaelKurowski  The cause of the cursor misplacement problem has been found: when the Terminal is initialized, it is not displayed in the browser view, resulting in a calculated character width of 0px, this calculation uses `getBoundingClientRect()`.

This problem will be fixed in the next version. @birdmanmandbir

**Comment by tzfun** [comment] 2023-03-27 07:17
`2.1.8` and `3.1.4` versions are fixed. @michaelKurowski

**Closed by tzfun** 2023-03-27 07:17 UTC
Labels: bug
